[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev" # or yarn dev
  
[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 