[build]
  command = "npm run build" # or yarn build
  publish = "dist" # or build/out/public depending on your framework
  
[dev]
  command = "npm run dev" # or yarn dev
  
[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 