[build]
  command = "npm run build"
  publish = "dist"
  
[dev]
  command = "npm run dev" # or yarn dev
  
[build.environment]
  NODE_VERSION = "22.14.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 